"""Tests for ``calfcord-package-agents``.

Same dry-run-based testing strategy as ``test_cli_tools``. One smoke test
(:meth:`TestDryRun.test_emits_dockerfile_for_real_agent`) runs against a
real shipped agent (``codex_demo``) to honour the CLI's promise —
"validate against the on-disk agents the user is about to ship." The
multi-agent, dedup, and name-validation cases use synthetic ``--context``
fixtures so they don't break when demo agents are added to or removed from
the repo's ``agents/`` directory.
"""

from __future__ import annotations

import io
from contextlib import redirect_stderr, redirect_stdout
from pathlib import Path

from calfkit_organization.packaging import cli_agents


def _run(argv: list[str]) -> tuple[int, str, str]:
    stdout, stderr = io.StringIO(), io.StringIO()
    code = 0
    try:
        with redirect_stdout(stdout), redirect_stderr(stderr):
            code = cli_agents.main(argv)
    except SystemExit as e:
        code = e.code if isinstance(e.code, int) else 1
    return code, stdout.getvalue(), stderr.getvalue()


def _write_agent(agents_dir: Path, name: str) -> None:
    """Write a minimal valid ``agents/<name>.md`` into ``agents_dir``."""
    agents_dir.mkdir(exist_ok=True)
    (agents_dir / f"{name}.md").write_text(
        f"---\nname: {name}\ndisplay_name: {name.title()}\n"
        f"description: Test agent {name}.\n---\nYou are {name}.\n"
    )


class TestDryRun:
    def test_emits_dockerfile_for_real_agent(self) -> None:
        # ``codex_demo`` is a shipped agent definition; this is the
        # closest-to-realistic dry run (validates against the real
        # repo-root agents/ directory).
        code, stdout, _ = _run(["codex_demo", "--tag", "test:1", "--dry-run"])
        assert code == 0
        assert "Generated by calfcord-package-agents" in stdout
        # The selective COPY is the defining feature of agent images;
        # verify it lands.
        assert "COPY agents/codex_demo.md ./agents/codex_demo.md" in stdout
        # The catch-all directory copy MUST NOT appear — that would
        # bring every agent in via the wildcard.
        assert "COPY agents ./agents" not in stdout

    def test_multiple_agents(self, tmp_path: Path) -> None:
        # Two distinct agents: synthetic fixtures so this doesn't depend
        # on how many demo agents currently ship in the repo.
        agents_dir = tmp_path / "agents"
        _write_agent(agents_dir, "alpha")
        _write_agent(agents_dir, "beta")
        code, stdout, _ = _run(
            ["alpha", "beta", "--tag", "test:1", "--dry-run", "--context", str(tmp_path)],
        )
        assert code == 0
        assert "COPY agents/alpha.md ./agents/alpha.md" in stdout
        assert "COPY agents/beta.md ./agents/beta.md" in stdout

    def test_duplicate_name_deduped(self, tmp_path: Path) -> None:
        agents_dir = tmp_path / "agents"
        _write_agent(agents_dir, "alpha")
        code, stdout, _ = _run(
            ["alpha", "alpha", "--tag", "test:1", "--dry-run", "--context", str(tmp_path)],
        )
        assert code == 0
        # Should appear exactly once in the COPY block.
        assert stdout.count("COPY agents/alpha.md") == 1


class TestNameValidation:
    def test_unknown_agent_exits_with_known_list(self, tmp_path: Path) -> None:
        agents_dir = tmp_path / "agents"
        _write_agent(agents_dir, "alpha")
        code, _, stderr = _run(
            ["definitely_not_an_agent", "--tag", "x:1", "--dry-run", "--context", str(tmp_path)],
        )
        assert code == 2
        assert "unknown agent" in stderr
        # The known list must surface so the operator can fix the typo.
        assert "alpha" in stderr

    def test_one_unknown_among_valid_still_fails(self, tmp_path: Path) -> None:
        agents_dir = tmp_path / "agents"
        _write_agent(agents_dir, "alpha")
        code, _, stderr = _run(
            ["alpha", "no_such_agent", "--tag", "x:1", "--dry-run", "--context", str(tmp_path)],
        )
        assert code == 2
        assert "no_such_agent" in stderr

    def test_missing_agents_dir_errors_with_actionable_message(self, tmp_path: Path) -> None:
        # If --context points at a directory with no agents/ subdir,
        # the CLI must say so concretely so the operator knows what to
        # fix (vs. crashing with an opaque traceback).
        code, _, stderr = _run(
            ["codex_demo", "--tag", "x:1", "--dry-run", "--context", str(tmp_path)],
        )
        assert code == 2
        assert "agents directory not found" in stderr

    def test_malformed_agent_md_surfaces_as_exit_2(self, tmp_path: Path) -> None:
        """An ``agents/<name>.md`` with bad frontmatter must fail the
        CLI build with an actionable message — that's the explicit
        rationale for using ``load_agents_dir`` over a bare
        ``Path.exists`` check (PR 5 design intent). Without this test
        a future refactor that swaps the validator for a file-only
        check would silently regress."""
        agents_dir = tmp_path / "agents"
        agents_dir.mkdir()
        # Invalid frontmatter: ``name`` must match the agent_id
        # pattern ``[a-z0-9_-]{1,32}``. Spaces fail validation.
        (agents_dir / "bad.md").write_text(
            "---\n"
            "name: 'bad name with spaces'\n"
            "display_name: Bad\n"
            "description: malformed for testing.\n"
            "---\n"
            "Body.\n"
        )
        code, _, stderr = _run(
            ["bad", "--tag", "x:1", "--dry-run", "--context", str(tmp_path)],
        )
        assert code == 2
        assert "cannot load agents" in stderr

    def test_malformed_yaml_syntax_surfaces_as_exit_2(self, tmp_path: Path) -> None:
        """An ``agents/<name>.md`` with YAML-parser-level breakage (not
        just field-validation breakage) must still fail with the
        friendly ``cannot load agents`` message. The previous
        regex-validation test exercises ``ValueError`` from Pydantic;
        this one exercises ``yaml.YAMLError`` from PyYAML — a different
        code path that escaped the narrowed ``except`` in cli_agents
        until ``parse_agent_md`` started normalising it to
        ``ValueError``. Without this case a future change that drops
        the normalisation would silently regress operator UX (raw
        traceback in place of the actionable message)."""
        agents_dir = tmp_path / "agents"
        agents_dir.mkdir()
        # Unterminated single-quoted string in YAML frontmatter — PyYAML
        # raises ``yaml.scanner.ScannerError`` (a ``YAMLError`` subclass).
        # The CLI's narrowed except catches ``ValueError`` only, so this
        # only succeeds if ``parse_agent_md`` normalises the YAMLError.
        (agents_dir / "broken.md").write_text(
            "---\n"
            "name: 'broken\n"
            "display_name: Broken\n"
            "description: broken YAML for testing.\n"
            "---\n"
            "Body.\n"
        )
        code, _, stderr = _run(
            ["broken", "--tag", "x:1", "--dry-run", "--context", str(tmp_path)],
        )
        assert code == 2
        assert "cannot load agents" in stderr


class TestArgparseSurface:
    def test_help_shows_usage(self) -> None:
        code, stdout, _ = _run(["--help"])
        assert code == 0
        assert "calfcord-package-agents" in stdout
        assert "--tag" in stdout

    def test_missing_tag_required(self) -> None:
        code, _, stderr = _run(["codex_demo"])
        assert code == 2
        assert "--tag" in stderr
