"""Tests for ``calfcord-package-agents``.

Same dry-run-based testing strategy as ``test_cli_tools``. Agent
validation reads from the real ``agents/`` directory at the repo
root (no fixtures) because the CLI's promise is "validate against
the on-disk agents the user is about to ship," not against a mock.
"""

from __future__ import annotations

import io
from contextlib import redirect_stderr, redirect_stdout
from pathlib import Path

from calfkit_organization.packaging import cli_agents


def _run(argv: list[str]) -> tuple[int, str, str]:
    stdout, stderr = io.StringIO(), io.StringIO()
    code = 0
    try:
        with redirect_stdout(stdout), redirect_stderr(stderr):
            code = cli_agents.main(argv)
    except SystemExit as e:
        code = e.code if isinstance(e.code, int) else 1
    return code, stdout.getvalue(), stderr.getvalue()


class TestDryRun:
    def test_emits_dockerfile_for_real_agent(self) -> None:
        # ``scribe`` is a shipped agent definition; this is the
        # closest-to-realistic dry run.
        code, stdout, _ = _run(["scribe", "--tag", "test:1", "--dry-run"])
        assert code == 0
        assert "Generated by calfcord-package-agents" in stdout
        # The selective COPY is the defining feature of agent images;
        # verify it lands.
        assert "COPY agents/scribe.md ./agents/scribe.md" in stdout
        # The catch-all directory copy MUST NOT appear — that would
        # bring every agent in via the wildcard.
        assert "COPY agents ./agents" not in stdout

    def test_multiple_agents(self) -> None:
        code, stdout, _ = _run(["scribe", "conan", "--tag", "test:1", "--dry-run"])
        assert code == 0
        assert "COPY agents/scribe.md ./agents/scribe.md" in stdout
        assert "COPY agents/conan.md ./agents/conan.md" in stdout

    def test_duplicate_name_deduped(self) -> None:
        code, stdout, _ = _run(["scribe", "scribe", "--tag", "test:1", "--dry-run"])
        assert code == 0
        # Should appear exactly once in the COPY block.
        assert stdout.count("COPY agents/scribe.md") == 1


class TestNameValidation:
    def test_unknown_agent_exits_with_known_list(self) -> None:
        code, _, stderr = _run(["definitely_not_an_agent", "--tag", "x:1", "--dry-run"])
        assert code == 2
        assert "unknown agent" in stderr
        # The known list must surface so the operator can fix the typo.
        assert "scribe" in stderr or "conan" in stderr

    def test_one_unknown_among_valid_still_fails(self) -> None:
        code, _, stderr = _run(
            ["scribe", "no_such_agent", "--tag", "x:1", "--dry-run"],
        )
        assert code == 2
        assert "no_such_agent" in stderr

    def test_missing_agents_dir_errors_with_actionable_message(self, tmp_path: Path) -> None:
        # If --context points at a directory with no agents/ subdir,
        # the CLI must say so concretely so the operator knows what to
        # fix (vs. crashing with an opaque traceback).
        code, _, stderr = _run(
            ["scribe", "--tag", "x:1", "--dry-run", "--context", str(tmp_path)],
        )
        assert code == 2
        assert "agents directory not found" in stderr

    def test_malformed_agent_md_surfaces_as_exit_2(self, tmp_path: Path) -> None:
        """An ``agents/<name>.md`` with bad frontmatter must fail the
        CLI build with an actionable message — that's the explicit
        rationale for using ``load_agents_dir`` over a bare
        ``Path.exists`` check (PR 5 design intent). Without this test
        a future refactor that swaps the validator for a file-only
        check would silently regress."""
        agents_dir = tmp_path / "agents"
        agents_dir.mkdir()
        # Invalid frontmatter: ``name`` must match the agent_id
        # pattern ``[a-z0-9_-]{1,32}``. Spaces fail validation.
        (agents_dir / "bad.md").write_text(
            "---\n"
            "name: 'bad name with spaces'\n"
            "slash: /bad\n"
            "display_name: Bad\n"
            "description: malformed for testing.\n"
            "---\n"
            "Body.\n"
        )
        code, _, stderr = _run(
            ["bad", "--tag", "x:1", "--dry-run", "--context", str(tmp_path)],
        )
        assert code == 2
        assert "cannot load agents" in stderr


class TestArgparseSurface:
    def test_help_shows_usage(self) -> None:
        code, stdout, _ = _run(["--help"])
        assert code == 0
        assert "calfcord-package-agents" in stdout
        assert "--tag" in stdout

    def test_missing_tag_required(self) -> None:
        code, _, stderr = _run(["scribe"])
        assert code == 2
        assert "--tag" in stderr
