"""Tests for ``calfcord-package-tools``.

The CLI's docker-buildx invocation is NOT exercised here — that would
need Docker-in-Docker in CI. Tests use ``--dry-run`` to validate name
resolution + Dockerfile rendering without spinning up a build.
"""

from __future__ import annotations

import io
from contextlib import redirect_stderr, redirect_stdout

import pytest

from calfkit_organization.packaging import cli_tools


def _run(argv: list[str]) -> tuple[int, str, str]:
    """Invoke ``cli_tools.main`` and capture stdout, stderr, exit code.

    Returns ``(exit_code, stdout, stderr)``. ``sys.exit`` from
    argparse / validation surfaces as ``SystemExit`` which we capture
    so the test can assert on its code.
    """
    stdout, stderr = io.StringIO(), io.StringIO()
    code = 0
    try:
        with redirect_stdout(stdout), redirect_stderr(stderr):
            code = cli_tools.main(argv)
    except SystemExit as e:
        code = e.code if isinstance(e.code, int) else 1
    return code, stdout.getvalue(), stderr.getvalue()


class TestDryRun:
    def test_emits_dockerfile_for_valid_tool(self) -> None:
        code, stdout, _ = _run(["shell", "--tag", "test:1", "--dry-run"])
        assert code == 0
        # The header banner is the most stable structural marker —
        # if the Dockerfile rendered, this line is in the output.
        assert "Generated by calfcord-package-tools" in stdout
        assert "Hosts ONLY: shell" in stdout

    def test_multiple_tools_in_one_image(self) -> None:
        code, stdout, _ = _run(["shell", "grep", "--tag", "test:1", "--dry-run"])
        assert code == 0
        # Both names baked into the env-var filter, alphabetically.
        assert "CALFCORD_TOOLS_INCLUDE=grep,shell" in stdout

    def test_duplicate_tool_name_deduped(self) -> None:
        code, stdout, _ = _run(["shell", "shell", "--tag", "test:1", "--dry-run"])
        assert code == 0
        # De-duplication: only one ``shell`` appears in the include
        # CSV regardless of how many times the user typed it.
        assert "CALFCORD_TOOLS_INCLUDE=shell\n" in stdout or \
               "CALFCORD_TOOLS_INCLUDE=shell " in stdout


class TestNameValidation:
    def test_unknown_tool_exits_with_known_list(self) -> None:
        code, _, stderr = _run(["definitely_not_a_tool", "--tag", "x:1", "--dry-run"])
        assert code == 2
        assert "unknown tool" in stderr
        # Known list MUST be in the error so the operator can fix the
        # typo without grepping the source tree.
        assert "shell" in stderr
        assert "private_chat" in stderr

    def test_one_unknown_among_valid_still_fails(self) -> None:
        code, _, stderr = _run(
            ["shell", "typo_tool", "--tag", "x:1", "--dry-run"],
        )
        assert code == 2
        assert "typo_tool" in stderr

    @pytest.mark.parametrize("known_tool", ["shell", "grep", "read_file", "private_chat"])
    def test_known_tools_accepted(self, known_tool: str) -> None:
        code, _, _ = _run([known_tool, "--tag", "x:1", "--dry-run"])
        assert code == 0


class TestArgparseSurface:
    def test_help_shows_usage(self) -> None:
        # ``--help`` exits 0 via SystemExit; argparse writes to stdout.
        code, stdout, _ = _run(["--help"])
        assert code == 0
        assert "calfcord-package-tools" in stdout
        assert "--tag" in stdout
        assert "--dry-run" in stdout

    def test_missing_tag_required(self) -> None:
        code, _, stderr = _run(["shell"])
        # argparse exits 2 on missing required arg.
        assert code == 2
        assert "--tag" in stderr

    def test_no_names_required(self) -> None:
        code, _, _ = _run(["--tag", "x:1"])
        assert code == 2  # argparse missing positional
