"""Unit tests for invoke_node_with_metadata.

The helper mirrors :meth:`Client.invoke_node` but sets
``state.metadata`` on the constructed :class:`State` before publish.
Tests assert behavior via a fake ``Client._invoke`` that captures the
constructed state, so we never need a real broker connection.
"""

from __future__ import annotations

from datetime import UTC, datetime
from unittest.mock import AsyncMock, MagicMock

import pytest

from calfkit_organization._compat.invoke import invoke_node_with_metadata
from calfkit_organization.agents.phonebook import PhonebookEntry
from calfkit_organization.bridge.wire import WireAuthor, WireMessage


def _wire() -> WireMessage:
    """A minimal valid WireMessage for envelope round-trip tests."""
    return WireMessage(
        event_id="abc",
        kind="slash",
        slash_target="scribe",
        message_id=1,
        channel_id=2,
        guild_id=3,
        content="hi",
        author=WireAuthor(
            discord_user_id=4,
            display_name="alice",
            is_bot=False,
            is_webhook=False,
        ),
        created_at=datetime(2025, 1, 1, tzinfo=UTC),
    )


def _phonebook_entry(agent_id: str = "scribe") -> PhonebookEntry:
    return PhonebookEntry(
        agent_id=agent_id,
        display_name="Scribe",
        description="Note-taking assistant.",
    )


def _client(reply_topic: str = "test.reply") -> MagicMock:
    """A fake :class:`Client` with the attributes our helper touches.

    Reads: ``client.reply_topic`` (property).
    Calls: ``client._invoke(...)`` (returns whatever AsyncMock returns).
    """
    client = MagicMock()
    client.reply_topic = reply_topic
    client._invoke = AsyncMock(return_value=MagicMock())
    return client


@pytest.mark.asyncio
class TestInvokeNodeWithMetadata:
    async def test_sets_metadata_on_state(self) -> None:
        client = _client()
        metadata = {"wire": {"event_id": "abc"}, "phonebook": [{"agent_id": "scribe"}]}

        await invoke_node_with_metadata(
            client,
            user_prompt="hi",
            topic="discord.ambient.in",
            metadata=metadata,
        )

        client._invoke.assert_awaited_once()
        kwargs = client._invoke.await_args.kwargs
        # The helper's whole job: state.metadata is populated before publish.
        assert kwargs["state"].metadata == metadata

    async def test_user_prompt_is_staged_on_state(self) -> None:
        client = _client()
        await invoke_node_with_metadata(
            client,
            user_prompt="hello world",
            topic="t.in",
            metadata={},
        )
        kwargs = client._invoke.await_args.kwargs
        # The staged message is what calfkit's Client.invoke_node does;
        # parity check.
        assert kwargs["state"].uncommitted_message is not None

    async def test_defaults_reply_topic_to_client_property(self) -> None:
        client = _client(reply_topic="auto.generated.reply")
        await invoke_node_with_metadata(
            client,
            user_prompt="hi",
            topic="t.in",
            metadata={},
        )
        kwargs = client._invoke.await_args.kwargs
        assert kwargs["reply_topic"] == "auto.generated.reply"

    async def test_explicit_reply_topic_overrides_default(self) -> None:
        client = _client(reply_topic="default.reply")
        await invoke_node_with_metadata(
            client,
            user_prompt="hi",
            topic="t.in",
            metadata={},
            reply_topic="custom.reply",
        )
        kwargs = client._invoke.await_args.kwargs
        assert kwargs["reply_topic"] == "custom.reply"

    async def test_explicit_correlation_id_is_passed_through(self) -> None:
        client = _client()
        await invoke_node_with_metadata(
            client,
            user_prompt="hi",
            topic="t.in",
            metadata={},
            correlation_id="fixed-id-123",
        )
        assert client._invoke.await_args.kwargs["correlation_id"] == "fixed-id-123"

    async def test_correlation_id_autogenerated_when_unset(self) -> None:
        client = _client()
        await invoke_node_with_metadata(
            client,
            user_prompt="hi",
            topic="t.in",
            metadata={},
        )
        cid = client._invoke.await_args.kwargs["correlation_id"]
        assert isinstance(cid, str)
        assert len(cid) > 0  # uuid7 hex

    async def test_deps_passed_through(self) -> None:
        client = _client()
        deps = {"discord": {"event_id": "x"}, "phonebook": []}
        await invoke_node_with_metadata(
            client,
            user_prompt="hi",
            topic="t.in",
            metadata={},
            deps=deps,
        )
        assert client._invoke.await_args.kwargs["deps"] == deps

    async def test_temp_instructions_on_state(self) -> None:
        client = _client()
        await invoke_node_with_metadata(
            client,
            user_prompt="hi",
            topic="t.in",
            metadata={},
            temp_instructions="be brief",
        )
        kwargs = client._invoke.await_args.kwargs
        assert kwargs["state"].temp_instructions == "be brief"

    async def test_model_settings_json_serializability_check(self) -> None:
        """Mirrors Client.invoke_node's JSON-serializability check on
        ``model_settings``."""
        client = _client()
        with pytest.raises(ValueError, match="not JSON-serializable"):
            await invoke_node_with_metadata(
                client,
                user_prompt="hi",
                topic="t.in",
                metadata={},
                model_settings={"bad": object()},  # type: ignore[dict-item]
            )


class TestMetadataEnvelope:
    """:class:`MetadataEnvelope` centralizes the ``state.metadata``
    schema so producers and consumers don't reimplement the
    WireMessage.model_validate dance. Tests pin the round-trip
    (typed-in, JSON-out, typed-back-in) and the error paths."""

    def test_wire_only_round_trips(self) -> None:
        from calfkit_organization._compat.invoke import (  # noqa: PLC0415
            MetadataEnvelope,
        )

        wire = _wire()
        envelope = MetadataEnvelope(wire=wire)
        encoded = envelope.model_dump(mode="json")
        round_tripped = MetadataEnvelope.extract(encoded)
        assert round_tripped == envelope
        # The wire round-trips back to a typed WireMessage (not a dict).
        assert isinstance(round_tripped.wire, WireMessage)
        assert round_tripped.wire.event_id == "abc"
        assert round_tripped.wire.kind == "slash"
        assert round_tripped.phonebook is None

    def test_wire_and_phonebook_round_trips(self) -> None:
        from calfkit_organization._compat.invoke import (  # noqa: PLC0415
            MetadataEnvelope,
        )

        wire = _wire()
        entry = _phonebook_entry()
        envelope = MetadataEnvelope(wire=wire, phonebook=[entry])
        encoded = envelope.model_dump(mode="json")
        round_tripped = MetadataEnvelope.extract(encoded)
        assert isinstance(round_tripped.wire, WireMessage)
        assert round_tripped.wire.event_id == "abc"
        assert round_tripped.phonebook is not None
        assert len(round_tripped.phonebook) == 1
        assert isinstance(round_tripped.phonebook[0], PhonebookEntry)
        assert round_tripped.phonebook[0].agent_id == "scribe"

    def test_accepts_wire_as_dict_via_pydantic_coercion(self) -> None:
        """Pydantic accepts a JSON-shaped dict for the typed ``wire``
        field (this is how the consumer side recovers from the
        on-the-wire JSON encoding produced by
        ``model_dump(mode="json")`` at publish)."""
        from calfkit_organization._compat.invoke import (  # noqa: PLC0415
            MetadataEnvelope,
        )

        wire_dict = _wire().model_dump(mode="json")
        envelope = MetadataEnvelope.extract({"wire": wire_dict})
        assert isinstance(envelope.wire, WireMessage)
        assert envelope.wire.event_id == "abc"

    def test_extract_rejects_non_dict(self) -> None:
        from calfkit_organization._compat.invoke import (  # noqa: PLC0415
            MetadataEnvelope,
        )

        with pytest.raises(ValueError, match="must be a dict"):
            MetadataEnvelope.extract(None)
        with pytest.raises(ValueError, match="must be a dict"):
            MetadataEnvelope.extract("a string")
        with pytest.raises(ValueError, match="must be a dict"):
            MetadataEnvelope.extract([1, 2, 3])

    def test_extract_rejects_missing_wire(self) -> None:
        from calfkit_organization._compat.invoke import (  # noqa: PLC0415
            MetadataEnvelope,
        )

        with pytest.raises(ValueError):
            MetadataEnvelope.extract({"phonebook": []})

    def test_extract_rejects_malformed_wire(self) -> None:
        """A wire dict that doesn't match :class:`WireMessage`'s
        schema (missing required fields, wrong types) surfaces at
        envelope construction now that ``wire`` is typed — consumers
        used to repeat ``WireMessage.model_validate`` themselves and
        catch ``ValidationError`` separately."""
        from calfkit_organization._compat.invoke import (  # noqa: PLC0415
            MetadataEnvelope,
        )

        with pytest.raises(ValueError):
            MetadataEnvelope.extract({"wire": {"bogus": "data"}})

    def test_frozen(self) -> None:
        from calfkit_organization._compat.invoke import (  # noqa: PLC0415
            MetadataEnvelope,
        )

        envelope = MetadataEnvelope(wire=_wire())
        with pytest.raises(ValueError):
            envelope.wire = _wire()  # type: ignore[misc]
