"""Render slim per-agent / per-tool Dockerfiles.

The shape mirrors the project's canonical ``Dockerfile`` exactly,
varying only three things:

1. The runtime stage's ``apt-get install`` list — narrowed by the
   per-tool OS-dep mapping (e.g. no ``tmux`` if ``shell`` isn't
   included, no ``ripgrep`` if neither ``grep`` nor ``glob`` is).
2. The builder's ``COPY agents`` line — for per-agent images, COPYs
   only the selected ``agents/<name>.md`` files rather than the whole
   directory.
3. The runtime ``ENV`` block — bakes ``CALFCORD_TOOLS_INCLUDE`` for
   per-tool images so the auto-discovery loader filters to just those
   tools at boot.

If the canonical ``Dockerfile`` is ever restructured, the constants in
this module must be updated to match. Tests in
``tests/packaging/test_dockerfile.py`` golden-test the output so drift
fails CI.

Pure Python, no external deps — the CLIs in this package can invoke
the templater without spinning up the full ``TOOL_REGISTRY``.
"""

from __future__ import annotations

from collections.abc import Iterable

# Always-on OS packages. ``ca-certificates`` is needed by any tool that
# talks HTTPS; ``git`` is small and ubiquitous enough that agents and
# operators expect it. Pulling either of these conditionally produced
# more bugs than image-size savings in early testing.
_ALWAYS_ON_OS_DEPS: tuple[str, ...] = ("ca-certificates", "git")

# Per-tool OS-dep mapping. Tools not listed here imply no extra OS
# packages — they're pure Python. When adding a new tool that needs an
# OS binary, add it here AND to the canonical Dockerfile so the
# all-in-one image keeps working.
_TOOL_OS_DEPS: dict[str, tuple[str, ...]] = {
    "shell": ("tmux",),
    "grep": ("ripgrep",),
    "glob": ("ripgrep",),
    # web_fetch / web_search only need ca-certificates, which is
    # always-on. Listed explicitly so the table is exhaustive.
    "web_fetch": (),
    "web_search": (),
    # FS tools and the in-memory tools have no extra OS deps.
    "read_file": (),
    "write_file": (),
    "edit_file": (),
    "todo_view": (),
    "todo_write": (),
    "private_chat": (),
}


def os_deps_for_tools(include_tools: Iterable[str]) -> list[str]:
    """Return the sorted union of OS package names needed for the given tools.

    Includes :data:`_ALWAYS_ON_OS_DEPS` regardless of the tool list.
    Unknown tool names are silently skipped — validation happens at the
    CLI layer, not here, so the templater stays loose-coupled to the
    live ``TOOL_REGISTRY``.
    """
    deps: set[str] = set(_ALWAYS_ON_OS_DEPS)
    for tool in include_tools:
        deps.update(_TOOL_OS_DEPS.get(tool, ()))
    return sorted(deps)


def _render_apt_install(packages: Iterable[str]) -> str:
    """Render the ``RUN apt-get install`` block with one package per line.

    Indentation matches the canonical Dockerfile (8 spaces) so the
    output diffs cleanly against the source-of-truth file.
    """
    lines = ["RUN apt-get update \\", " && apt-get install -y --no-install-recommends \\"]
    for pkg in packages:
        lines.append(f"        {pkg} \\")
    lines.append(" && rm -rf /var/lib/apt/lists/*")
    return "\n".join(lines)


def _generated_header(*, kind: str, names: Iterable[str]) -> str:
    """Banner at the top of every generated Dockerfile.

    Tells the reader this file is build-tool output, names the inputs
    that produced it (so a copy on disk is self-describing), and
    points at the canonical source for any non-templated changes.
    """
    name_list = ", ".join(sorted(names))
    return (
        f"# Generated by calfcord-package-{kind} for: {name_list}\n"
        f"# DO NOT EDIT by hand — regenerate via the CLI. The canonical\n"
        f"# source is the project's top-level ``Dockerfile``; this file\n"
        f"# is templated from ``src/calfkit_organization/packaging/dockerfile.py``.\n"
    )


def render_tools_dockerfile(
    *,
    include_tools: list[str],
    registry_keys: list[str],
) -> str:
    """Render a Dockerfile for an image hosting only ``include_tools``.

    Args:
        include_tools: Tool schema names to include. Must be a subset
            of ``registry_keys`` — validation is the CLI's job; this
            function trusts its input.
        registry_keys: The full set of known tool names. Used to
            stamp the file's header comment for forensic value
            (an operator inspecting a built image can tell which
            calfcord version produced it).

    Returns:
        The complete Dockerfile content as a string, ready to write
        to a tempdir and feed to ``docker buildx build``.
    """
    _ = registry_keys  # currently unused; kept for the header-stamping plan
    apt_block = _render_apt_install(os_deps_for_tools(include_tools))
    include_csv = ",".join(sorted(include_tools))
    header = _generated_header(kind="tools", names=include_tools)

    return f"""{header}
# syntax=docker/dockerfile:1.7
#
# Per-tool calfcord image. Hosts ONLY: {include_csv}
#
# Tools subscribe to ``tool.<name>.input`` topics; this image's
# ``calfkit-tools`` worker subscribes only to the listed names because
# the ``CALFCORD_TOOLS_INCLUDE`` env var (baked below) filters the
# auto-discovery walk in ``tools/discovery.py``.


# ── builder ──────────────────────────────────────────────────────────────────
FROM python:3.12-slim AS builder

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /usr/local/bin/

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1

COPY pyproject.toml uv.lock README.md ./
RUN --mount=type=cache,target=/root/.cache/uv \\
    uv sync --frozen --no-dev --no-install-project

COPY src ./src
RUN --mount=type=cache,target=/root/.cache/uv \\
    uv sync --frozen --no-dev


# ── runtime ──────────────────────────────────────────────────────────────────
FROM python:3.12-slim AS runtime

# OS packages narrowed to those the included tools actually use.
{apt_block}

ARG UID=1000
ARG GID=1000
RUN groupadd --gid ${{GID}} calfcord \\
 && useradd  --uid ${{UID}} --gid ${{GID}} --create-home --shell /bin/bash calfcord

WORKDIR /app

ENV PATH=/app/.venv/bin:$PATH \\
    PYTHONUNBUFFERED=1 \\
    PYTHONDONTWRITEBYTECODE=1 \\
    CALFCORD_TOOLS_INCLUDE={include_csv}

COPY --from=builder --chown=calfcord:calfcord /app /app

USER calfcord

# Per-tool images default to the tools entry point. The bridge / agent
# / router entry points are still on PATH (same image, same venv) but
# don't make sense here — running ``calfkit-bridge`` in a tools-only
# image would try to load ``agents/*.md`` which isn't in this image.
CMD ["calfkit-tools"]
"""


def render_agents_dockerfile(
    *,
    include_agents: list[str],
) -> str:
    """Render a Dockerfile for an image hosting only ``include_agents``.

    Args:
        include_agents: Agent names (filename stems, e.g. ``["scribe",
            "conan"]``). Validation against on-disk ``agents/<name>.md``
            files is the CLI's job.

    Returns:
        Complete Dockerfile content. Differs from
        :func:`render_tools_dockerfile` in three places:

        * No ``CALFCORD_TOOLS_INCLUDE`` (agent images don't host tools).
        * No ``tmux`` / ``ripgrep`` (same reason).
        * The ``COPY agents`` line names individual files instead of
          the whole directory, so the image's ``/app/agents/`` only
          contains the selected agents.
    """
    # Agent images don't host tools, so no tool-driven OS deps.
    apt_block = _render_apt_install(_ALWAYS_ON_OS_DEPS)
    header = _generated_header(kind="agents", names=include_agents)
    # COPY each agent's .md file individually. Sorted for deterministic
    # layer hashes — same inputs produce byte-identical Dockerfiles.
    agent_copy_lines = "\n".join(
        f"COPY agents/{name}.md ./agents/{name}.md" for name in sorted(include_agents)
    )

    return f"""{header}
# syntax=docker/dockerfile:1.7
#
# Per-agent calfcord image. Hosts ONLY: {", ".join(sorted(include_agents))}
#
# The image's ``/app/agents/`` contains only the listed agent .md
# files. ``calfkit-agent`` loads whatever's present, so no runtime
# filter is needed — the filesystem IS the filter.


# ── builder ──────────────────────────────────────────────────────────────────
FROM python:3.12-slim AS builder

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /usr/local/bin/

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1

COPY pyproject.toml uv.lock README.md ./
RUN --mount=type=cache,target=/root/.cache/uv \\
    uv sync --frozen --no-dev --no-install-project

COPY src ./src
RUN --mount=type=cache,target=/root/.cache/uv \\
    uv sync --frozen --no-dev

# Per-agent COPY: only the .md files explicitly named in the build
# command end up in the image. Agents not in the list literally
# don't exist inside this container.
RUN mkdir -p ./agents
{agent_copy_lines}


# ── runtime ──────────────────────────────────────────────────────────────────
FROM python:3.12-slim AS runtime

# OS packages: agent images don't run tool bodies, so no tmux/ripgrep.
{apt_block}

ARG UID=1000
ARG GID=1000
RUN groupadd --gid ${{GID}} calfcord \\
 && useradd  --uid ${{UID}} --gid ${{GID}} --create-home --shell /bin/bash calfcord

WORKDIR /app

ENV PATH=/app/.venv/bin:$PATH \\
    PYTHONUNBUFFERED=1 \\
    PYTHONDONTWRITEBYTECODE=1

COPY --from=builder --chown=calfcord:calfcord /app /app

USER calfcord

CMD ["calfkit-agent"]
"""
